"""Kamus normalisasi slang — DIHASILKAN OTOMATIS, JANGAN DISUNTING TANGAN.

Sumber  : docs/tables/token_normalisasi_terisi.csv (diisi manusia, gerbang H-5)
Pembuat : python -m ml.src.build_slang_dict

SLANG_DICT memetakan token informal ke daftar token baku. Nilainya berupa list
karena sebagian pemetaan menghasilkan lebih dari satu kata
(mis. "gabisa" -> ["tidak", "bisa"]).

NOISE_TOKENS dibuang sepenuhnya, tidak dinormalisasi.
"""

SLANG_DICT: dict[str, list[str]] = {
    'driver': ['pengemudi'],
    'di': ['di'],
    'nya': ['nya'],
    'yg': ['yang'],
    'ga': ['tidak'],
    'gak': ['tidak'],
    'ok': ['oke'],
    'ke': ['ke'],
    'udah': ['sudah'],
    'good': ['bagus'],
    'gofood': ['gofood'],
    'drivernya': ['pengemudinya'],
    'ya': ['ya'],
    'promo': ['promo'],
    'nunggu': ['menunggu'],
    'gopay': ['gopay'],
    'pake': ['pakai'],
    'cancel': ['batal'],
    'go': ['go'],
    'dapet': ['dapat'],
    'gk': ['tidak'],
    'apk': ['aplikasi'],
    'gocar': ['gocar'],
    'bgt': ['sangat'],
    'udh': ['sudah'],
    'customer': ['pelanggan'],
    'sampe': ['sampai'],
    'klo': ['kalau'],
    'resto': ['restoran'],
    'terimakasih': ['terima', 'kasih'],
    'ongkir': ['ongkos', 'kirim'],
    'dulu': ['dulu'],
    'sy': ['saya'],
    'tp': ['tapi'],
    'chat': ['chat'],
    'fitur': ['fitur'],
    'cs': ['layanan', 'pelanggan'],
    'rb': ['ribu'],
    'dpt': ['dapat'],
    'karna': ['karena'],
    'food': ['food'],
    'voucher': ['voucher'],
    'up': ['up'],
    'batalin': ['batalkan'],
    'gabisa': ['tidak', 'bisa'],
    'promonya': ['promonya'],
    'gimana': ['bagaimana'],
    'tdk': ['tidak'],
    'ribet': ['ribet'],
    'gw': ['saya'],
    'update': ['pembaruan'],
    'gitu': ['begitu'],
    'lg': ['lagi'],
    'bener': ['benar'],
    'best': ['terbaik'],
    'grab': ['grab'],
    'goride': ['goride'],
    'nyari': ['mencari'],
    'hp': ['ponsel'],
    'mulu': ['terus'],
    'the': ['the'],
    'respon': ['respons'],
    'jd': ['jadi'],
    'mantab': ['mantap'],
    'dr': ['dari'],
    'jg': ['juga'],
    'ngga': ['tidak'],
    'trus': ['terus'],
    'nice': ['bagus'],
    'app': ['aplikasi'],
    'nggak': ['tidak'],
    'gara': ['gara-gara'],
    'sdh': ['sudah'],
    'login': ['login'],
    'cepet': ['cepat'],
    'gopaylater': ['gopaylater'],
    'pdhl': ['padahal'],
    'dibatalin': ['dibatalkan'],
    'si': ['si'],
    'job': ['pekerjaan'],
    'utk': ['untuk'],
    'dgn': ['dengan'],
    'males': ['malas'],
    'mesen': ['memesan'],
    'gosend': ['gosend'],
    'an': ['sekitar'],
    'tpi': ['tapi'],
    'banyakin': ['perbanyak'],
    'km': ['kilometer'],
    'ny': ['nya'],
    'eh': ['eh'],
    'paylater': ['paylater'],
    'rating': ['rating'],
    'ngasih': ['memberi'],
    'skrg': ['sekarang'],
    'jgn': ['jangan'],
    'no': ['nomor'],
    'makasih': ['terima', 'kasih'],
    'dicancel': ['dibatalkan'],
    'lu': ['kamu'],
    'later': ['later'],
    'ni': ['ini'],
    'tetep': ['tetap'],
    'tuh': ['itu'],
    'error': ['error'],
    'krn': ['karena'],
    'maps': ['peta'],
    'deket': ['dekat'],
    'gajelas': ['tidak', 'jelas'],
    'gaada': ['tidak', 'ada'],
    'sya': ['saya'],
    'blm': ['belum'],
    'yaa': ['ya'],
    'online': ['online'],
    'ojol': ['ojek', 'online'],
    'service': ['layanan'],
    'ku': ['saya'],
    'in': ['in'],
    'trs': ['terus'],
    'mantul': ['mantap'],
    'bs': ['bisa'],
    'laper': ['lapar'],
    'ongkirnya': ['ongkos', 'kirimnya'],
    'org': ['orang'],
    'download': ['unduh'],
    'lgi': ['lagi'],
    'ngambil': ['mengambil'],
    'admin': ['admin'],
    'car': ['car'],
    'knp': ['kenapa'],
    'sm': ['sama'],
    'express': ['ekspres'],
    'baguss': ['bagus'],
    'dg': ['dengan'],
    'so': ['so'],
    'notif': ['notifikasi'],
    'dateng': ['datang'],
    'bngt': ['sangat'],
    'dri': ['dari'],
    'gomart': ['gomart'],
    'dlm': ['dalam'],
    'jos': ['mantap'],
    'nungguin': ['menunggu'],
    'make': ['pakai'],
    'bug': ['bug'],
    'uninstall': ['uninstall'],
    'dll': ['dll'],
    'ujan': ['hujan'],
    'jdi': ['jadi'],
    'costumer': ['pelanggan'],
    'ride': ['ride'],
    'aplikator': ['aplikator'],
    'mantapp': ['mantap'],
    'double': ['ganda'],
    'pay': ['pay'],
    'gojeg': ['gojek'],
    'ngotak': ['masuk', 'akal'],
    'yah': ['ya'],
    'bnyk': ['banyak'],
    'dipake': ['dipakai'],
    'ad': ['ada'],
    'ko': ['kok'],
    'slalu': ['selalu'],
    'is': ['adalah'],
    'ilang': ['hilang'],
    'bnyak': ['banyak'],
    'skrng': ['sekarang'],
    'mager': ['malas', 'bergerak'],
    'argo': ['tarif'],
    'kaga': ['tidak'],
    'gamau': ['tidak', 'mau'],
    'pak': ['pak'],
    'kl': ['kalau'],
    'muter': ['berputar'],
    'nerima': ['menerima'],
    'nyampe': ['sampai'],
    'simple': ['sederhana'],
    'milih': ['memilih'],
    'ngak': ['tidak'],
    'dlu': ['dulu'],
    'krna': ['karena'],
    'urgent': ['urgent'],
    'upgrade': ['upgrade'],
    'gercep': ['cepat'],
    'gofoodnya': ['gofood-nya'],
    'trimakasih': ['terima', 'kasih'],
    'pke': ['pakai'],
    'internet': ['internet'],
    'dn': ['dan'],
    'bgus': ['bagus'],
    'mantappp': ['mantap'],
    'mantep': ['mantap'],
    'engga': ['tidak'],
    'lbh': ['lebih'],
    'rp': ['rupiah'],
    'donk': ['dong'],
    'restonya': ['restorannya'],
    'pdhal': ['padahal'],
    'smpe': ['sampai'],
    'topup': ['top', 'up'],
    'aj': ['saja'],
    'byk': ['banyak'],
    'tgl': ['tanggal'],
    'thanks': ['terima', 'kasih'],
    'bangett': ['sangat'],
    'comfort': ['nyaman'],
    'masukin': ['masukkan'],
    'pick': ['pick'],
    'nolak': ['menolak'],
    'nomer': ['nomor'],
    'gausah': ['tidak', 'usah'],
    'to': ['to'],
    'gmn': ['bagaimana'],
    'tu': ['itu'],
    'cash': ['tunai'],
    'nambah': ['menambah'],
    'on': ['on'],
    'otp': ['otp'],
    'maxim': ['maxim'],
    'uninstal': ['uninstall'],
    'benerin': ['perbaiki'],
    'ttp': ['tetap'],
    'lo': ['kamu'],
    'very': ['sangat'],
    'ngk': ['tidak'],
    'tambahin': ['tambahkan'],
    'adain': ['adakan'],
    'google': ['google'],
    'malem': ['malam'],
    'apl': ['aplikasi'],
    'tips': ['tip'],
    'you': ['kamu'],
    'bsa': ['bisa'],
    'cm': ['cuma'],
    'and': ['dan'],
    'bagusss': ['bagus'],
    'apps': ['aplikasi'],
    'wa': ['whatsapp'],
    'pakek': ['pakai'],
    'nyusahin': ['menyusahkan'],
    'sma': ['sama'],
    'ktp': ['ktp'],
    'mntap': ['mantap'],
    'bnget': ['sangat'],
    'instal': ['instal'],
    'mnt': ['menit'],
    'loading': ['loading'],
    'narik': ['mengemudi'],
    'nunggunya': ['menunggunya'],
    'pemberitahuan': ['pemberitahuan'],
    'sgt': ['sangat'],
    'ngebantu': ['membantu'],
    'time': ['waktu'],
    'drive': ['drive'],
    'tf': ['transfer'],
    'acc': ['setujui'],
    'full': ['penuh'],
    'nganter': ['mengantar'],
    'nyaa': ['nya'],
    'plat': ['pelat'],
    'shopee': ['shopee'],
    'slot': ['slot'],
    'aktifitas': ['aktivitas'],
    'okee': ['oke'],
    'qris': ['qris'],
    'supir': ['pengemudi'],
    'gatau': ['tidak', 'tahu'],
    'josss': ['mantap'],
    'msh': ['masih'],
    'far': ['far'],
    'asik': ['asyik'],
    'cpt': ['cepat'],
    'drever': ['pengemudi'],
    'kyk': ['seperti'],
    'nemu': ['menemukan'],
    'user': ['pengguna'],
    'siip': ['sip'],
    'apknya': ['aplikasinya'],
    'gtu': ['begitu'],
    'thank': ['terima', 'kasih'],
    'wkwk': ['tertawa'],
    'plis': ['tolong'],
    'booking': ['pemesanan'],
    'ngeselin': ['menyebalkan'],
    'smua': ['semua'],
    'bangettt': ['sangat'],
    'cust': ['pelanggan'],
    'emng': ['memang'],
    'hrs': ['harus'],
    'klu': ['kalau'],
    'sllu': ['selalu'],
    'hehe': ['tertawa'],
    'emg': ['memang'],
    'rame': ['ramai'],
    'mantaap': ['mantap'],
    'jakarta': ['jakarta'],
    'nyesel': ['menyesal'],
    'server': ['server'],
    'dapetnya': ['dapatnya'],
    'knpa': ['kenapa'],
    'ngeluh': ['mengeluh'],
    'pt': ['pt'],
    'yaaa': ['ya'],
    'balikin': ['kembalikan'],
    'dpet': ['dapat'],
    'vocer': ['voucher'],
    'goto': ['goto'],
    'hadeh': ['aduh'],
    'discount': ['diskon'],
    'nyangkut': ['tersangkut'],
    'byr': ['bayar'],
    'pd': ['pada'],
    'xl': ['xl'],
    'gocarnya': ['gocar-nya'],
    'markotop': ['mantap'],
    'ngelag': ['lag'],
    'trima': ['terima'],
    'ah': ['ah'],
    'nanya': ['bertanya'],
    'ngaco': ['kacau'],
    'refund': ['pengembalian', 'dana'],
    'gps': ['gps'],
    'jt': ['juta'],
    'ksh': ['kasih'],
    'mantaf': ['mantap'],
    'pickup': ['jemput'],
    'tbtb': ['tiba-tiba'],
    'woi': ['woi'],
    'jga': ['juga'],
    'pdahal': ['padahal'],
    'love': ['suka'],
    'tokopedia': ['tokopedia'],
    'dh': ['sudah'],
    'joss': ['mantap'],
    'mikir': ['berpikir'],
    'nggk': ['tidak'],
    'woy': ['woy'],
    'attitude': ['sikap'],
    'pinjol': ['pinjaman', 'online'],
    'cmn': ['cuma'],
    'dtg': ['datang'],
    'gacor': ['bagus'],
    'mo': ['mau'],
    'segitu': ['sebanyak', 'itu'],
    'fast': ['cepat'],
    'klw': ['kalau'],
    'temen': ['teman'],
    'gmna': ['bagaimana'],
    'nyoba': ['mencoba'],
    'call': ['telepon'],
    'gopinjam': ['gopay', 'pinjam'],
    'maksa': ['memaksa'],
    'bye': ['selamat', 'tinggal'],
    'gapernah': ['tidak', 'pernah'],
    'ngebug': ['bug'],
    'recommended': ['direkomendasikan'],
    'alesan': ['alasan'],
    'by': ['oleh'],
    'goceng': ['lima', 'ribu'],
    'okey': ['oke'],
    'send': ['send'],
    'tks': ['terima', 'kasih'],
    'vouchernya': ['vouchernya'],
    'nga': ['tidak'],
    'ngerti': ['mengerti'],
    'ngirim': ['mengirim'],
    'system': ['sistem'],
    'jln': ['jalan'],
    'klau': ['kalau'],
    'wifi': ['wi-fi'],
    'mart': ['mart'],
    'smoga': ['semoga'],
    'mlh': ['malah'],
    'mw': ['mau'],
    'nyasar': ['tersesat'],
    'center': ['center'],
    'da': ['ada'],
    'for': ['untuk'],
    'ngomong': ['berbicara'],
    'responnya': ['responsnya'],
    'review': ['ulasan'],
    'spam': ['spam'],
    'telp': ['telepon'],
    'tlg': ['tolong'],
    'tlp': ['telepon'],
    'bru': ['baru'],
    'mksh': ['terima', 'kasih'],
    'nganterin': ['mengantar'],
    'okay': ['oke'],
    'bales': ['balas'],
    'expres': ['ekspres'],
    'gojekk': ['gojek'],
    'offline': ['offline'],
    'rejeki': ['rezeki'],
    'all': ['semua'],
    'diem': ['diam'],
    'trims': ['terima', 'kasih'],
    'wow': ['wow'],
    'cansel': ['batal'],
    'fiturnya': ['fiturnya'],
    'game': ['game'],
    'mantaaap': ['mantap'],
    'anj': ['anjing'],
    'delay': ['delay'],
    'okeh': ['oke'],
    'php': ['pemberi', 'harapan', 'palsu'],
    'please': ['tolong'],
    'aktifin': ['aktifkan'],
    'ijo': ['hijau'],
    'kemaren': ['kemarin'],
    'orng': ['orang'],
    'suspend': ['suspend'],
    'bgtt': ['sangat'],
    'ehh': ['eh'],
    'gopaynya': ['gopay-nya'],
    'lho': ['lho'],
    'sebenernya': ['sebenarnya'],
    'ajah': ['saja'],
    'belagu': ['sombong'],
    'jm': ['jam'],
    'lgsg': ['langsung'],
    'nah': ['nah'],
    'naikin': ['naikkan'],
    'out': ['out'],
    'gt': ['begitu'],
    'instant': ['instan'],
    'komplen': ['komplain'],
    'telfon': ['telepon'],
    'cancle': ['batal'],
    'csnya': ['layanan', 'pelanggannya'],
    'like': ['suka'],
    'mapsnya': ['petanya'],
    'sll': ['selalu'],
    'sorry': ['maaf'],
    'vermuk': ['verifikasi', 'wajah'],
    'close': ['menutup'],
    'play': ['play'],
    'vocher': ['voucher'],
    'wkwkwk': ['tertawa'],
    'bnr': ['benar'],
    'complain': ['komplain'],
    'ngisi': ['mengisi'],
    'overall': ['secara', 'keseluruhan'],
    'ud': ['sudah'],
    'bgs': ['bagus'],
    'kelaperan': ['kelaparan'],
    'knapa': ['kenapa'],
    'kya': ['seperti'],
    'lag': ['lag'],
    'menggangu': ['mengganggu'],
    'scam': ['penipuan'],
    'sihh': ['sih'],
    'sngat': ['sangat'],
    'this': ['ini'],
    'thx': ['terima', 'kasih'],
    'blom': ['belum'],
    'kluar': ['keluar'],
    'nyebelin': ['menyebalkan'],
    'aamiin': ['amin'],
    'ndak': ['tidak'],
    'ontime': ['tepat', 'waktu'],
    'ui': ['ui'],
    'bbrp': ['beberapa'],
    'lamaa': ['lama'],
    'mageran': ['malas', 'bergerak'],
    'nyantol': ['terhubung'],
    'pelayananya': ['pelayanannya'],
    'rmh': ['rumah'],
    'worth': ['sepadan'],
    'dc': ['debt', 'collector'],
    'mantaps': ['mantap'],
    'ngebatalin': ['membatalkan'],
    'otw': ['dalam', 'perjalanan'],
    'rs': ['rumah', 'sakit'],
    'supirnya': ['pengemudinya'],
    'tsb': ['tersebut'],
    'ugal': ['ugal-ugalan'],
    'applikasi': ['aplikasi'],
    'duluan': ['lebih', 'dulu'],
    'gosen': ['gosend'],
    'lahh': ['lah'],
    'thn': ['tahun'],
    'voucer': ['voucher'],
    'goofood': ['gofood'],
    'install': ['instal'],
    'ntah': ['entah'],
    'ojolnya': ['ojek', 'onlinenya'],
    'satset': ['cepat'],
    'smpai': ['sampai'],
    'ai': ['ai'],
    'gopaypinjam': ['gopay', 'pinjam'],
    'gpp': ['tidak', 'apa-apa'],
    'ap': ['aplikasi'],
    'aplication': ['aplikasi'],
    'appp': ['aplikasi'],
    'aps': ['aplikasi'],
    'bberapa': ['beberapa'],
    'bgitu': ['begitu'],
    'blgnya': ['bilangnya'],
    'brg': ['barang'],
    'bua': ['buat'],
    'bukannnya': ['bukannya'],
    'bukanya': ['bukannya'],
    'customers': ['pelanggan'],
    'danpuas': ['dan', 'puas'],
    'datengnya': ['datangnya'],
    'dianter': ['diantar'],
    'dianterin': ['diantar'],
    'diksh': ['dikasih'],
    'disejutuin': ['disetujui'],
    'diskonanya': ['diskonnya'],
    'disumpai': ['disumpahi'],
    'disuru': ['disuruh'],
    'dtivernya': ['pengemudinya'],
    'emang': ['memang'],
    'eror': ['error'],
    'gada': ['tidak', 'ada'],
    'gini': ['begini'],
    'gmapnsudah': ['google', 'maps', 'sudah'],
    'gpay': ['gopay'],
    'gua': ['saya'],
    'haga': ['harga'],
    'hdehh': ['haduh'],
    'jahat': ['jahat'],
    'jir': ['anjir'],
    'jkrta': ['jakarta'],
    'kalo': ['kalau'],
    'kasian': ['kasihan'],
    'kimbek': ['sialan'],
    'kmbuh': ['kambuh'],
    'kmrn': ['kemarin'],
    'kmudian': ['kemudian'],
    'kslamatan': ['keselamatan'],
    'kurng': ['kurang'],
    'latter': ['later'],
    'lebihin': ['melebihkan'],
    'lelet': ['lambat'],
    'lnjut': ['lanjut'],
    'mantapz': ['mantap'],
    'mao': ['mau'],
    'menguhungi': ['menghubungi'],
    'mn': ['mana'],
    'mtornya': ['motornya'],
    'ngecek': ['cek'],
    'ngerampok': ['merampok'],
    'ngibulin': ['menipu'],
    'ngorder': ['memesan'],
    'ntapss': ['mantap'],
    'nyiapin': ['menyiapkan'],
    'orange': ['orang'],
    'padahan': ['padahal'],
    'pelayana': ['pelayanan'],
    'pemudi': ['pengemudi'],
    'pemudian': ['pengemudi'],
    'pengen': ['ingin'],
    'pnya': ['punya'],
    'rekomen': ['rekomendasi'],
    'sampek': ['sampai'],
    'sampenya': ['sampainya'],
    'sendri': ['sendiri'],
    'seneng': ['senang'],
    'seperi': ['seperti'],
    'skali': ['sekali'],
    'tau': ['tahu'],
    'td': ['tadi'],
    'th': ['tahun'],
    'tidka': ['tidak'],
    'top': ['bagus'],
    'turup': ['tutup'],
    'uda': ['sudah'],
    'veri': ['sangat'],
    'wiffi': ['wifi'],
}

NOISE_TOKENS: frozenset[str] = frozenset({
    'ber',
    'la',
    'ma',
    'meow',
    'nge',
    'se',
})
